### ISSUE TITLE
Sort lines preserving separator

### ISSUE THREAD

**Issue by eahanson** [biati-digital/nova-text-tools#10]
How about a line sort feature that preserves line separators?

```
bat,
cat,
ant
```

would be sorted to:

```
ant,
bat,
cat
```

The algorithm might be something like, "if all the lines except the last contain the same non-whitespace non-alphanumeric character, then after sorting remove that character from end of the last line and add it to the end of any other line that doesn't have it".

This would be super useful for languages that don't support trailing commas in lists.

**Comment by biati-digital** [comment]
Hi, that's a great idea, unfortunately my license already expired and i'm not planning to renew soon, i went back to PHP Storm. 

I'll try Nova again in 1/2 years.

**Comment by eahanson** [comment]
I created my own extension for this: https://extensions.panic.com/extensions/eahanson/eahanson.smart-sort-lines/
