### ISSUE TITLE
"Filter Unique Lines" removes the duplicated lines without one remaining

### ISSUE THREAD

**Issue by guillaumealgis** [biati-digital/nova-text-tools#13]
From my understanding the command "Filter Unique Lines" should remove duplicated occurence of a same line, while keeping a unique occurence in the file (like the unix `uniq` program does).

However, the command completely removes all occurrences of a line :

https://user-images.githubusercontent.com/1041337/174351523-b5f8eebf-8f2a-459f-9012-3222dfa3070d.mov

**Comment by biati-digital** [comment]
There's a "Delete duplicate lines" command, please check the readme for explanation of some commands including.

**Comment by biati-digital** [comment]
Hi, the name of the commands are not based on a Unix tool, all the extensions I've tried in multiple text editor use "Delete duplicates" so we use that.
