### ISSUE TITLE
Consider adding aliases commands for identifier case conventions?

### ISSUE THREAD

**Issue by guillaumealgis** [biati-digital/nova-text-tools#15]
I was searching for the command to transform some text to `some-text`, after testing a few names I had in mind, I had to pull up my browser and open this repo's README to find out that the command is named "Make param case".

I don't find the name to be super obvious (but that maybe just me). Would you be open to adding commands with alternative names for common naming conventions ?

For example [Wikipedia](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Examples_of_multiple-word_identifier_formats) lists the following conventions and names:

| Formatting | Name(s) |
|------------|---------|
| `twowords` | flatcase |
| `TWOWORDS` | UPPERCASE |
| `twoWords` | (lower) camelCase, dromedaryCase |
| `TwoWords` | PascalCase, UpperCamelCase, StudlyCase |
| `two_words` | snake_case, pothole_case |
| `TWO_WORDS` | SCREAMING SNAKE CASE, MACRO_CASE, CONSTANT_CASE |
| `two_Words` | camel_Snake_Case |
| `Two_Words` | Pascal_Snake_Case, Title_Case |
| `two-words` | kebab-case, dash-case, lisp-case, spinal-case |
| `TWO-WORDS` | TRAIN-CASE, COBOL-CASE, SCREAMING-KEBAB-CASE |
| `Two-Words` | Train-Case, HTTP-Header-Case |

I'm not advocating to add all names, but maybe a few (popular) options would be a win?

I'm aware that it could also cause confusion if too many commands have the same effect, but I think it's worth considering.

**Comment by biati-digital** [comment]
Hi, Sure, i'm open to rename some commands, specially the `param case` command  (did you search for kebab case before checking the readme?)

I do not like the idea of creating aliases, as you mention, it can cause confusion but for a couple of commands i think it's ok, at least for some time, if the Nova API improves and allows some keywords in the commands to improve search results or until people get used to the new names.

- `Param Case` **should be renamed** to `Kebab Case` (i do not think people search param case) honestly i do not even remember why i used that name. I do not use Nova a lot so never thought about this.
- `Train Case` **as alias** of the current command `Header Case`
- `Screaming Snake Case` **as alias** of the current command `Constant Case`
- `Flatcase` not sure if the same as the command `No Case`, currently the `No Case` command allows spaces, not sure if `Flatcase` should remove all spaces. If same add **as alias** of `No Case`


The following are not handled by this extension yet but should be really easy to implement:
- Screaming Kebab Case `TWO-WORDS`
- Pascal Snake Case `two_Words`
- camel Snake Case `two_Words`
- Flat case `twowords`? if different from `No Case`  

Let me know what you think.
