### ISSUE TITLE
Encoding HTML Entities is missing some

### ISSUE THREAD

**Issue by tomliv** [biati-digital/nova-text-tools#19]
I have a similar extension for Code that will sometimes encode a 'curly/smart' single quote as `&apos;` or `&rsquo;`. Your extension, I am assuming, is unaware of one of those as it frequently misses single quotes. Unfortunately I do not have a readily available example.

**Comment by tomliv** [comment]
Just tested this and your extension did convert `&apos;` so maybe `&rsquo;` is missing?

**Comment by biati-digital** [comment]
Hi, if you are able to provide some examples that would be great or you can submit a PR if you manage to fix it.

**Comment by biati-digital** [comment]
Closing as no more info was provided. Anyway, we've ported this extension to VS Code in case you want to try it.
[https://marketplace.visualstudio.com/items?itemName=biati.vscode-text-tools](https://marketplace.visualstudio.com/items?itemName=biati.vscode-text-tools)
