### ISSUE TITLE
Categorize functions via submenus or separators

### ISSUE THREAD

**Issue by Gummibando** [biati-digital/nova-text-tools#2]
Categories via submenus (Sort…, Case…m Filter… etc.) and/or separators would be great.
Currently, the menu is really unwieldy due to its length, in my case way exceeding the screen height of a 13" MBP.

**Comment by biati-digital** [comment]
That's a good idea, unfortunately it's not possible to create submenus, the Nova API only allow us to register the commands and Nova displays the list in different sections like the app menu, fortunately the separator is possible.

(Quick test for separators)
![CleanShot 2021-09-14 at 17 00 28](https://user-images.githubusercontent.com/1219228/133339890-3ea8f8b4-06a1-4217-b01d-8fe8e5fa1b73.png)

I'll improve and reorder the list and add separators to make it easier to read.

**Comment by biati-digital** [comment]
This has been updated in the latest update (2.0.0), check for updates in the nova extensions window

![CleanShot 2021-09-21 at 21 38 28](https://user-images.githubusercontent.com/1219228/134274886-76faf15a-8867-4b5a-b4d8-6dd1208062ad.png)
