### ISSUE TITLE
Feature request: Gremlins

### ISSUE THREAD

**Issue by tomliv** [biati-digital/nova-text-tools#22]
One big blocker for me to use Nova full-time is the lack of an extension that does what this one does for Code: https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins

It would be awesome if you could add this feature.

**Comment by biati-digital** [comment]
thanks for the feature request but I’m not sure this functionality should be part of this extension, it should not be hard to port the vscode version but i barely use Nova so i can not invest the time to do it.
