### ISSUE TITLE
Nova Extension Service Crash

### ISSUE THREAD

**Issue by gingerbeardman** [biati-digital/nova-text-tools#23]
![Screen shot 2023-08-01 at 15 51 58](https://github.com/biati-digital/nova-text-tools/assets/49612/e75b0f7b-66fc-4e2e-88ec-8dc4d22c0331)

[NovaExtensionService-2023-08-01-155147.ips.zip](https://github.com/biati-digital/nova-text-tools/files/12230952/NovaExtensionService-2023-08-01-155147.ips.zip)

Also reported to Nova.

**Comment by biati-digital** [comment]
were you executing a command (included with this extension) when the extension service crashed?

**Comment by gingerbeardman** [comment]
Not as far as I am aware, no.

**Comment by biati-digital** [comment]
Then it's probably not related to the extension as on start it simply register the available commands and that's all.

I don't think we can do anything to help in this case, it's probably better to notify Panic.

**Comment by gingerbeardman** [comment]
Still happening regularly.

Notifying you and Panic

> Extension Service Quit Unexpectedly

https://imgur.com/UszNDKr

[Archive.zip](https://github.com/biati-digital/nova-text-tools/files/12487163/Archive.zip)
