### ISSUE TITLE
Disable/enable commands one by one

### ISSUE THREAD

**Issue by certainlyakey** [biati-digital/nova-text-tools#24]
Hi, thanks for the great plugin! 

One request – I am using another plugin for managing text case conversion, but I really like other commands offered by Text Tools. Would it be possible to add a simple configuration pane where we could disable unused commands? Right now I have commands from both plugins cluttering the Command Palette.

**Comment by biati-digital** [comment]
I do not think that's possible, commands must be registered in a static json file [extension.json](https://github.com/biati-digital/nova-text-tools/blob/master/texttools.novaextension/extension.json)

Maybe you can modify your installed version to remove those commands or fork this extension and modify it to your needs.

Can i ask why are you using another extension for case conversion?

**Comment by certainlyakey** [comment]
Hey @biati-digital! I am using a different one because in Text Tools there's a problem where if you haven't got any text selected, then the case change applies to all the words in a file. This sometimes goes unnoticed, so I decided to use another plugin for now.
