### ISSUE TITLE
Make Title Case doesn't work on UPPERCASE string

### ISSUE THREAD

**Issue by adocehic** [biati-digital/nova-text-tools#4]
I use case conversion to sanitize text that I work with. Often, text I grab happens to have fully uppercase titles/headings. I rely on tools like this to speed up my workflow.

Replicate issue by:
Select string of uppercase text;
Right click > Text Tools > Make Title Case

Expectation:
Selected text converted to title case;

What happens:
Selected text remains uppercase;

A fix would be to have the Make Title Case script first run a make-lowercase prior to changing to uppercase.

Thanks!

**Comment by biati-digital** [comment]
Hi, that could work, can you please post a few examples (replicate and Expectation) so we can copy/paste and make some tests?

**Comment by adocehic** [comment]
Sure thing!

Input: "GIZA AND LOUVRE ADDED TO THE MONUMENT COLLECTION"
**Expectation:** "Giza and Louvre Added to the Monument Collection"
_Actual result from Make Title Case:_ "GIZA AND LOUVRE ADDED TO THE MONUMENT COLLECTION"

Input: "MEET COUTURE LUXURY FLOORING"
**Expectation:** "Meet Couture Luxury Flooring"
_Actual result from Make Title Case:_ "MEET COUTURE LUXURY FLOORING"

**Comment by biati-digital** [comment]
Thank you, making it lower case first fixes this issue, i'm preparing an update that will include this fix.

**Comment by adocehic** [comment]
Thanks team!

**Comment by biati-digital** [comment]
This has been fixed in the latest update (2.0.0), check for updates in the nova extensions window

![CleanShot 2021-09-21 at 21 38 28](https://user-images.githubusercontent.com/1219228/134274886-76faf15a-8867-4b5a-b4d8-6dd1208062ad.png)
