### ISSUE TITLE
Sorting Mangles Text Selected In Vim Mode

### ISSUE THREAD

**Issue by clintonbloodworth** [biati-digital/nova-text-tools#9]
1. Enable Vim mode.
1. Open a non-empty editor.
1. Press `V` to enter visual mode.
1. Press `J` or `K` to select lines downward or upward.
1. Sort the lines.

Nova: 355205.
Text Tools: 3.0.6.

**Comment by biati-digital** [comment]
Sorry, my license already expired and i do not have plans to renew it as the editor still lacks a lot of functionality and has a lot of bugs so for now i can not invest more time with an editor i'm no longer using. 

The development of our Nova extensions has been paused until i can (hopefully) use Nova as my main editor.
